version: 2

sources:
  - name: mds
    description: Banco replica da adventure works
    schema: sap_adw
    tables:
      - name: salesorderheader
        description: Uma linha por pedido de venda.
        columns:
        - name: salesorderid
          description: e a chave primaria da tabela salesorderheader
          tests:
          - unique
          - not_null
          

      - name: product
        description: Produtos.

      - name: salesorderdetail
        description: Detalhe de pedidos

      - name: creditcard
        description: Cartão de credito.

      - name: salesreason
        description: Motivo de venda.

      - name: salesorderheadersalesreason
        description: cabecalho do Motivo de venda.
      
      - name: customer
        description: taela de Cliente

      - name: person
        description: taela de Pessoa

      - name: address
        description: taela de endereco.


      - name: stateprovince
        description: taela de provincia do estado.

      - name: countryregion
        description: taela de regiao do pais

      - name: businessentitycontact
        description: taela de entidade comercial

      - name: store
        description: dados da loja
      

      
      
